### PR TITLE
feat: add `template-dir` argument for custom templates

### PR DESCRIPTION
**Pull request by rcebrian**
Generate ```template-dir``` as a new input to include custom template parameter (-t | --template)

- [x] Tested in my own repository
- [x] Docs included

Trying to include the templates using 'command-args':
```yml
jobs
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: rust
          openapi-file: test_data/openapi.json
          command-args: |
            -t my-template
```
Generates an error because the templates path wasn't correct, needing the full path of the workdir, that is not included anywhere, having to access the code to look for it.
With this change, we can use:
```yml
jobs
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: rust
          openapi-file: test_data/openapi.json
          template-dir: my-template
```

I hope it helps.

### CODE REVIEW

**Review by dbanty — COMMENTED** [review]
Awesome, thanks for the contribution! One question I have is where these templates came from. They're too thorough to have been written just for this test (I think), so I assume they were copied from another project which would mean we're in violation of whatever the license was for that project (presumably).

Is it possible to have a simpler (maybe single file) template just for this test? I don't know how strict the openapitools validation is on templates.

**Comment by rcebrian** [comment]
> Genial, gracias por el aporte! Una pregunta que tengo es de dónde provienen estas plantillas. Son demasiado completos para haber sido escritos solo para esta prueba (creo), así que asumo que fueron copiados de otro proyecto, lo que significaría que estamos violando la licencia para ese proyecto (presumiblemente).
> 
> ¿Es posible tener una plantilla más simple (quizás un solo archivo) solo para esta prueba? No sé qué tan estricta es la validación de openapitools en las plantillas.

**Comment by rcebrian** [comment]
> Awesome, thanks for the contribution! One question I have is where these templates came from. They're too thorough to have been written just for this test (I think), so I assume they were copied from another project which would mean we're in violation of whatever the license was for that project (presumably).
> 
> Is it possible to have a simpler (maybe single file) template just for this test? I don't know how strict the openapitools validation is on templates.

You're welcome!
I have obtained the templates from the official repository https://github.com/OpenAPITools/openapi-generator which is under the Apache license, so you can use them.

On the other hand, I also tried to generate a minor template, but I got multiple errors and the generated code was not reliable.

**Comment by dbanty** [comment]
> I have obtained the templates from the official repository https://github.com/OpenAPITools/openapi-generator which is under the Apache license, so you can use them.

Great, so if it's Apache I think the rules are we need to include a copy of the license anywhere we've copied the code. So just copying the license into that templates dir is probably okay then.

**Comment by rcebrian** [comment]
> > I have obtained the templates from the official repository https://github.com/OpenAPITools/openapi-generator which is under the Apache license, so you can use them.
> 
> Great, so if it's Apache I think the rules are we need to include a copy of the license anywhere we've copied the code. So just copying the license into that templates dir is probably okay then.

Ok, added!

**Review by dbanty — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
