### PR TITLE
Updated README with the correct tool name.

### PR DESCRIPTION
**Pull request by synchronizing**
Thank you for the project. Small update to fix the example given in the README.md.

### CODE REVIEW

**Comment by emann** [comment]
Thanks so much @synchronizing!

**Comment by synchronizing** [comment]
Thank you as well. With your package in mind I created [`fastapi-openapi-specs-action`](https://github.com/column-street/fastapi-openapi-specs-action) to generate the FastAPI OpenAPI specs file via GitHub action. Combining both of them gives a powerful tool to automatically generate FastAPI clients via Github Actions.

**Comment by emann** [comment]
@synchronizing FYI if you're looking to create python clients we've made [our own python client generator](https://github.com/triaxtec/openapi-python-client) thats written in python and is more up to date with modern practices/tools/etc. (our favorite of which is type hints + mypy). It even has [its own action](https://github.com/triaxtec/openapi-python-client-action) as well!

**Comment by synchronizing** [comment]
> @synchronizing FYI if you're looking to create python clients we've made [our own python client generator](https://github.com/triaxtec/openapi-python-client) thats written in python and is more up to date with modern practices/tools/etc. (our favorite of which is type hints + mypy). It even has [its own action](https://github.com/triaxtec/openapi-python-client-action) as well!

Thank you for the share! Just skimmed through the README, and wondering (didn't notice it) if the tool supports asynchronous client generation. 

One of the requirements my team and I have is asynchronous clients.

**Comment by emann** [comment]
@synchronizing Yep! Every client generated has both sync and async methods for each endpoint.

**Comment by synchronizing** [comment]
Man, I have to share... after generating code with the OpenAPI-Generator vs you guys project, I must say, my team and I are definitely sticking with what you guys built. Much appreciate for pointing me towards that path.

**Pull request merged**
